### ISSUE TITLE
NDK location not found.

### ISSUE THREAD

**Issue by preethamsridhar** [named-data-mobile/NFD-android#1]
I am trying to compile this code in Mac OS X. When I try to build. I am getting this error. 
Error:(122) A problem occurred evaluating project ':app'.

> NDK location not found. Define location with ndk.dir in the local.properties file or with an ANDROID_NDK_ROOT environment variable.

I have downloaded the latest version of ndk and assigned the path to ndk.dir in local.properties files. 
What could be the problem.

The same problem with the sdk too.

**Comment by cawka** [comment]
Have you followed the readme?  Specifically "Building" section as it is instructing how to properly create local.properties file with configuration of sdk and ndk.

Just in case. You should use the latest version of CrystaX ndk (not ndk released by google directly), as it has several required imrpvements.

**Comment by preethamsridhar** [comment]
Till now I was using the ndk released by google. 
Now i downloaded the crystax as it was in readme. 
The same problem is with sdk too.

below is the screen shot of local.properties.
![snip20150707_1](https://cloud.githubusercontent.com/assets/8992041/8561807/ca5d958e-24f8-11e5-984f-89395a65f310.png)

**Comment by cawka** [comment]
The instructions are for the command-line build.  Building from within Android Studio requires successful gradle sync (which on your picture I see failed for some reason).

**Comment by preethamsridhar** [comment]
In any case do you know how to solve the issue?

**Comment by cawka** [comment]
Build from the command line or properly synchronize gradle in android studio :)

**Comment by preethamsridhar** [comment]
Is there any document to build the ndk for mac? If you dont mind could you share it with me!!

**Comment by preethamsridhar** [comment]
I have specified ndk.dir in the local.properties. This works in windows system but not in MAC OS X. Can anybody tell me the reason!

**Comment by clovisystem** [comment]
s[o tm burro aqui
