### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by nowfalsalahudeen** [named-data-mobile/NFD-android#2]
```
jni/ndn-cxx.mk:117: jni/cryptopp/Android.mk: No such file or directory
make.exe: Entering directory `W:/Android tests/NFD-android-master/app/src/main'
Android NDK: jni/Android.mk: Cannot find module with tag 'boost/1.57.0' in import path    
jni/ndn-cxx.mk:119: *** Android NDK: Aborting.    .  Stop.
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
make.exe: Leaving directory `W:/Android tests/NFD-android-master/app/src/main'
:app:ndkBuild FAILED
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Users\Admin_Zeekoi\Downloads\crystax-ndk-10.3.1/ndk-build.cmd'' finished with non-zero exit value 2
```

am stuck with this error..plz help me

**Comment by cawka** [comment]
There are known issues to compile NFD-android on Windows and I wouldn't recommend it (there is a workaround, but it is not simple).  Try using the vagrant environment for that.

**Comment by cawka** [comment]
Additional information.  I have checked and there are several issues with compilation against CrystaX NDK 10.3.1.  For now, you need to use an older version, e.g., 10.2.1.

**Comment by nowfalsalahudeen** [comment]
yeah..used 10.2.1 ..but got another error..

make.exe: Entering directory `W:/Android tests/NFD new/app/src/main'
make.exe: *** No rule to make target`jni/ndn-cxx/src/data.cpp', needed by `obj/local/arm64-v8a/objs/ndn-cxx/ndn-cxx/src/data.o'.  Stop.
make.exe: Leaving directory`W:/Android tests/NFD new/app/src/main'
Error:Execution failed for task ':app:ndkBuild'.

> Process 'command 'W:\crystax-ndk-10.2.1/ndk-build.cmd'' finished with non-zero exit value 2
> :app:ndkBuild FAILED

@cawka ..take a look this

**Comment by cawka** [comment]
This is the complication of windows platform.  If you really really really want to compile on windows, then you will need to manually copy content of `app/src/main/jni/ndn-cxx/src` to `app/src/main/jni/ndn-cxx-android/ndn-cxx`  (on other platforms, the symlink addresses this issue).

In any case. I would again discourage compilation on Windows :)

---

A related note.  I have pushed two new commits.  If you would like to take them, you will need to switch back to the newest version of CrystaX (10.3.1)---the relevant readme and vagrant scripts has been updated.

**Comment by nowfalsalahudeen** [comment]
thank you so much..

**Comment by nowfalsalahudeen** [comment]
and i have successfully compiled this on ubuntu. But the generated apk(app/build/outputs) gives parsing error when install it on android device .(output folder contains all architectures apk..all are giving this same parsing error )..why?

**Comment by cawka** [comment]
I'm not sure why this can be happening.  Which version you have assembled: release or debug (`gradle assembleRelease` or `gradle assembleDebug`?  The release version will not work (and shouldn't compile) without proper configuration of signing keys.  The debug version should work, but may require enabling "debug" apps in android settings.

You can ask gradle to install the proper .apk file automatically:

```
gradle installDebug
```

**Comment by nowfalsalahudeen** [comment]
am using this code for release build (gradle assembleRelease).. i have only experiance with android studio..its the first time to compile android projrct on linux distro without IDE..
will assembleDebug  works? 
and i want to change the target sdk to 23.so can i change it in build.gradle or write something similer on another file?

**Comment by cawka** [comment]
`gradle installDebug` will compile in debug mode and install on the connected device (this is almost exactly what IDE does).

Are there any reason to switch target SDK to 23?  And yes, you can simply update build.gradle, and if you're using Android Studio, you will need to "synchronize" gradle (it usually asks when change is detected).

**Comment by nowfalsalahudeen** [comment]
thanks again

**Comment by nowfalsalahudeen** [comment]
and i need to sign apk..ho can i achieve that..i mean create keystore

**Comment by cawka** [comment]
Check `README-dev.md`
