### ISSUE TITLE
Needs Updating

### ISSUE THREAD

**Issue by changcc5** [named-data-mobile/NFD-android#4]
1. There is jni error when building from the source. 
2. Needs to take out the beta name for gradle in build.gradle
3. Vagrant can't build, and script can't build, and source method can't build
   3.1. Only way to build right now is use the script to pull project from that link in the building script, and change the build gradle to just version 2.0.

**Comment by cawka** [comment]
Thanks. Will try to update asap.

**Comment by rodyu** [comment]
The script still cannot build because of jni error.
Also, I've seen crystax-ndk-10.2.1 is recommended in other issue, but there is no build-target-openssl.sh file in crystax-ndk-10.2.1. How should I create prebuilt OpenSSL libraries?
I think I might need some help. Thank you.

**Comment by cawka** [comment]
Where did you see a recommendation of 10.2.1?  The readme and all the script refer to 10.**3**.1 and the already compiled openssl libraries for this version of NDK can be downloaded here https://github.com/named-data-mobile/crystax-prebuilt-openssl

**Comment by rodyu** [comment]
[https://github.com/named-data-mobile/NFD-android/issues/2](url)
The recommendation is in the comment on 22 Jan 2016.
Is there no compilation problem against CrystaX NDK 10.3.1 now?

Additionally, I still cannot build NFD-android. Could you provide me with instructions to build it?
Thank you.

**Comment by cawka** [comment]
README.md file has instructions.  You can also follow Travis-CI build (starting point in .travis.yml, which uses scripts from .jenkins.d).

**Comment by rodyu** [comment]
.jenkins.d could build sucessfully.  :)
Another question, I've installed NFD-Android on Google Play, but I don't know how to use it.
Is there any documentation to which I can refer?
Thank you.

**Comment by cawka** [comment]
Unfortunately, we don't have much documentation yet (still in progress).  You try to play with a demo project that uses NFD on Android platform: https://github.com/named-data-mobile/apps-NDN-Whiteboard (you can check out demo GIFs https://github.com/named-data-mobile/apps-NDN-Whiteboard/tree/master/DemoGIFs)

**Comment by rodyu** [comment]
For now, I ran NFD-Android and NDN-Whiteboard on two devices; unfortunately, I would get an error message(ERROR: Timeout trying). My understanding is that two devices should be connected through NFD-Android and data can be transferred then. Is it correct?

I've tried to add faces and routes among devices, but I would also get an error message(Error communicating with NFD(Action failed, forwarder returned: 504 Connect failed: No route to host)).
How can I add faces and routes among devices correctly?
Thank you.

**Comment by rodyu** [comment]
For now, I ran NFD-Android and NDN-Whiteboard on two devices; unfortunately, I would get an error message(ERROR: Timeout trying). My understanding is that two devices are connected through adding each other's face and route, and data can be transferred then. Is it correct?

Besides, I used PC to register one device and it was successful in name registration; while I got "face creation failed : Requested endpoint is prohibited (code 406)" when using PC to register the other device. What might be the cause of the problem?
Thank you.

**Comment by rodyu** [comment]
In order to connect two devices through NFD-Android, I've tried many ways, but NDN-Whiteboard still couldn't run successfully. I was stuck in problem for few days.  Would you please teach me how to finish the setup between two devices?
Thank you.
